### ISSUE TITLE
waiting for fix issue

### ISSUE THREAD

**Issue by ebzrvf** [SakuraNotStupid/sunst0rm-Linux#3]
guys, you can write when the sunstorm comes out, I'm very patiently waiting❤️‍🔥

**Comment by mineek** [comment]
It isnt possible for linux for now, install macOS and use my original repo to use it.

**Comment by ebzrvf** [comment]
Okay bro, thanks

**Comment by SakuraNotStupid** [comment]
It isnt possible work in Linux, cause of hdiutil can't make kernel read or write on Linux
